---
argument_specs:
  main:
    short_description: "Set up workload monitoring"
    options:
      coreweave_monitoring_host:
        description: Target host address
        type: str
        required: true
      coreweave_monitoring_username:
        description: Authentication username
        type: str
      coreweave_monitoring_password:
        description: Authentication password
        type: str
      coreweave_monitoring_api_key:
        description: API key for authentication
        type: str
      coreweave_monitoring_validate_certs:
        description: Validate SSL certificates
        type: bool
        default: true
      coreweave_monitoring_state:
        description: Desired state
        type: str
        default: present
        choices: [present, absent]
