---
# tasks/main.yml for coreweave_gpu_provision
# Provision GPU instances with storage

- name: Validate required variables
  ansible.builtin.assert:
    that:
      - coreweave_gpu_provision_host is defined
    fail_msg: "coreweave_gpu_provision_host must be defined"
    quiet: true

- name: Execute coreweave gpu provision
  ansible.builtin.debug:
    msg: >-
      Provision GPU instances with storage.
      Target: {{ coreweave_gpu_provision_host }}
